name: Elixir CI
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    name: Linux OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["25", "24"]
        elixir: ["1.14", "1.13"]
    services:
      redis:
        image: redis:6-alpine
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile --force --warnings-as-errors
      - name: Check format
        run: mix format --check-formatted
      - name: Run Tests
        run: mix test
